---
name: test demo workflow YAML
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "This is a test demo workflow"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Job 2 test is running"
